[graph]
all-features = true
targets = [
  "aarch64-pc-windows-msvc",
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
]

[advisories]
version = 2
ignore = []
unmaintained = "all"
unsound = "all"
unused-ignored-advisory = "deny"
yanked = "deny"

[licenses]
version = 2
allow = ["Apache-2.0", "MIT"]
confidence-threshold = 1.0
exceptions = []
include-build = true
include-dev = true
unused-allowed-license = "deny"

[licenses.private]
ignore = false

[bans]
highlight = "all"
multiple-versions = "deny"
multiple-versions-include-dev = true
skip = []
skip-tree = []
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
required-git-spec = "rev"
unknown-git = "deny"
unknown-registry = "deny"
unused-allowed-source = "deny"
