
[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = false
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = false
publish = true
semver_check = true

[[package]]
name = "xtask"
release = false
publish = false

[changelog]
protect_breaking_commits = true
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
