additional_cargo_args = ["--locked", "--all-features"]
additional_cargo_test_args = ["--", "--test-threads=1"]
timeout_multiplier = 5.0
minimum_test_timeout = 60.0
gitignore = true
cap_lints = false
test_tool = "cargo"
exclude_re = [
  '^src/core_logic\.rs:[0-9]+:[0-9]+: replace proofs::quoting_length_is_bounded with \(\)$',
  '^src/core_logic\.rs:[0-9]+:[0-9]+: replace proofs::two_bit_replacement_changes_only_its_field with \(\)$',
  '^src/core_logic\.rs:[0-9]+:[0-9]+: replace << with >> in proofs::two_bit_replacement_changes_only_its_field$',
  '^src/core_logic\.rs:[0-9]+:[0-9]+: replace proofs::one_bit_replacement_changes_only_its_field with \(\)$',
  '^src/core_logic\.rs:[0-9]+:[0-9]+: replace << with >> in proofs::one_bit_replacement_changes_only_its_field$',
]
